### ISSUE TITLE
training seems slow if train 200k epochs

### ISSUE THREAD

**Issue by wztdream** [addtt/attend-infer-repeat-pytorch#4]
Hi,
Thank you for this great repo:)

Both the paper and your repo train multi-minist for 200k epochs, do we really need so much epoch? Should it be 200k steps? Or 200 epoch? And in my machine one rtx3090, one epoch took about 20s, so 200k epoch will took about 40 days! I also noticed other repo, like [pyro](https://pyro.ai/examples/air.html), they use one Tesla K80, which is outdated gpu compared with rtx3090, and they only take 4 hours to train 200k epochs.

So, is this setting 200k epoch correct here? How long did you use for train 200k epoch?

**Comment by addtt** [comment]
Hi, thanks for reaching out and sorry for the delay - I didn't see the notification! 

It should be 200k steps, not epochs :) That's what they do on the pyro tutorial as well (see the plots at the end).

I don't remember how long it took, but 200k steps should definitely not take too long. 

Good luck!

**Comment by wztdream** [comment]
thank you, this makes sense
